version: '3.8'

services:
  db:
    image: postgres
    container_name: my_postgres
    environment:
      POSTGRES_USER: ecomapp
      POSTGRES_PASSWORD: ecomapp123
      POSTGRES_DB: mydb
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
    driver: local
